name: GitHub Pages

on:
  push:
    branches:
      - main  # oder der Branch, den du verwenden möchtest

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0'  # oder eine andere Ruby-Version
    - name: Install dependencies
      run: |
        bundle install
    - name: Build the site
      run: |
        bundle exec jekyll build
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_site
